server:
  port: 8188

spring:
  profiles:
    active: dev
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: root
#    url: jdbc:mysql://121.41.50.100:3306/data_center?autoReconnect=true&rewriteBatchedStatements=true&characterEncoding=UTF-8&allowMultiQueries=true&&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#
mybatis:
  mapper-locations: classpath:mybatis/mapper/dc/*.xml
  type-aliases-package: com.qyc.model